.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, README.md
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>
=> Issue Templates added

.github/slack.yaml
fixes #2 
Signed-off-by: ashiscs <ashissingh640@gmail.com>
=> Added Slack Notifier for Github Stars

Makefile, cmd/manager/main.go, go.mod, pkg/servicemesh/istio/istio.go
- Basic Go project scaffold
Signed-off-by: Nitish Malhotra <nitish.malhotra@gmail.com>
=> Create project scaffolding

Makefile, cmd/meshsync/main.go, go.mod, internal/controller/controller.go, pkg/meshsync/istio/istio.go
Signed-off-by: crustyy <muskanbansal919@gmail.com>
=> changed GO mod project name to meshery-operator

README.md
A project logo for the Meshery Operator with MeshSync at its heart.
_MeshSync Inside™_
Fixes #15
=> Adding Meshery Operator Logo

README.md
Signed-off-by: Adeola <46505882+Adeola-Adesoba@users.noreply.github.com>
=> Change Layer5 Contributor to Layer5 Community

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Signed-off-by: anita-ihuman <charlesanita403@gmail.com>
=> added release drafter to the repository

go.mod, go.sum, pkg/meshsync/istio/pipeline.go, pkg/meshsync/istio/virtual_service.go
Signed-off-by: Dev Kalra <kalradev@outlook.com>
Pipeline structure for istio discovery
=> added istio discovery structure

go.mod, go.sum, pkg/meshsync/cluster/pipeline/pipeline.go, pkg/meshsync/meshes/istio/pipeline/pipeline.go, pkg/meshsync/service/discovery.go, pkg/meshsync/service/service.go
Signed-off-by: Dev Kalra <kalradev@outlook.com>
Implemented Discovery Code
=> added discovery code in service package

pkg/meshsync/cluster/pipeline/pipeline.go, pkg/meshsync/meshes/istio/pipeline/pipeline.go, pkg/meshsync/service/discovery.go, pkg/meshsync/service/service.go
=>  Kalradev/meshsync/service

go.mod, go.sum, pkg/message/nats/nats.go
Signed-off-by: Dev Kalra <kalradev@outlook.com>
Implemented a wrapper over Nats. 
=> implemented nats client

go.mod, go.sum, pkg/broker/broker.go, pkg/broker/nats/nats.go, pkg/informers/informer.go, pkg/meshsync/cluster/cluster.go, pkg/meshsync/cluster/informers/informer.go, pkg/meshsync/cluster/pipeline/cluster.go, pkg/meshsync/cluster/pipeline/deployment.go, pkg/meshsync/cluster/pipeline/namespace.go, pkg/meshsync/cluster/pipeline/node.go, pkg/meshsync/cluster/pipeline/pipeline.go, pkg/meshsync/cluster/pipeline/pod.go, pkg/meshsync/controller.go, pkg/meshsync/meshes/istio/informers/informers.go, pkg/meshsync/meshes/istio/istio.go, pkg/meshsync/meshes/istio/pipeline/authorization_policy.go, pkg/meshsync/meshes/istio/pipeline/destination_rule.go, pkg/meshsync/meshes/istio/pipeline/envoy_filter.go, pkg/meshsync/meshes/istio/pipeline/gateway.go, pkg/meshsync/meshes/istio/pipeline/istio.go, pkg/meshsync/meshes/istio/pipeline/peer_authentication.go, pkg/meshsync/meshes/istio/pipeline/pipeline.go, pkg/meshsync/meshes/istio/pipeline/request_authentication.go, pkg/meshsync/meshes/istio/pipeline/service_entry.go, pkg/meshsync/meshes/istio/pipeline/sidecar.go, pkg/meshsync/meshes/istio/pipeline/virtual_service.go, pkg/meshsync/meshes/istio/pipeline/workload_entry.go, pkg/meshsync/meshes/istio/pipeline/workload_group.go, pkg/meshsync/meshsync.go
Signed-off-by: Dev Kalra <kalradev@outlook.com>
Added code to start informers
Broker: Nats implementation
Added code for publishing messages to cluster and istio pipeline
=> code for running informers

.github/workflows/slack.yaml
=> fix Slack notify on Star

.github/workflows/slack.yaml
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>
=> correct usage of env

.github/workflows/build-and-release.yml, .github/workflows/ci.yml, Dockerfile, Makefile
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
This PR fixes #84 
=> feat: initiate docker build and push for operator

Makefile, api/v1alpha1/broker_types.go, api/v1alpha1/common.go, api/v1alpha1/meshsync_types.go, config/certmanager/kustomization.yaml, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_webhook_patch.yaml, config/manager/kustomization.yaml, config/manifests/crd.yaml, config/manifests/default.yaml, config/manifests/rbac.yaml, config/prometheus/kustomization.yaml, config/rbac/kustomization.yaml, config/samples/kustomization.yaml, config/samples/meshery_v1alpha1_broker.yaml, config/samples/meshery_v1alpha1_meshsync.yaml, config/webhook/kustomization.yaml
=> modified yaml files

Makefile, config/default/kustomization.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/manifests/default.yaml, config/manifests/rbac.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_client_clusterrole.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, config/webhook/service.yaml, pkg/client/client.go, pkg/client/v1alpha1/broker.go, pkg/client/v1alpha1/meshsync.go, pkg/client/v1alpha1/v1apha1.go
=> added kubernetes client for custom resurces

main.go, pkg/client/client.go, pkg/client/v1alpha1/broker.go, pkg/client/v1alpha1/meshsync.go, pkg/client/v1alpha1/v1apha1.go
=> client fixes

config/manifests/default.yaml, pkg/broker/broker.go, pkg/broker/resources.go
=> fixes for the docker image

pkg/broker/broker.go
=> fixes for the ci

config/manifests/default.yaml
=> fixed image id

config/manifests/default.yaml, config/samples/meshery_v1alpha1_broker.yaml, config/samples/meshery_v1alpha1_meshsync.yaml, controllers/broker_controller.go, controllers/error.go, controllers/meshsync_controller.go, go.sum, main.go, pkg/broker/broker.go
=> reconcillation fixes

config/manager/manager.yaml, config/manifests/default.yaml, pkg/meshsync/resources.go
=> image tag fixed

config/samples/meshery_v1alpha1_broker.yaml, controllers/broker_controller.go, controllers/meshsync_controller.go, go.mod, go.sum, pkg/meshsync/resources.go
=> minor tweaks

pkg/broker/broker.go
=> fixes for internal endpoint for meshsync

config/manifests/default.yaml
=> bug fix for clusterrole

config/manifests/default.yaml, controllers/broker_controller.go, controllers/meshsync_controller.go, main.go, pkg/broker/broker.go
Minikube hyperkit driver Ip conflict fixed.
=> fix for minikube hyperkit

config/manifests/default.yaml, controllers/broker_controller.go, controllers/meshsync_controller.go, main.go, pkg/broker/broker.go
Reverts layer5io/meshery-operator#131
=> Revert "fix for minikube hyperkit"

pkg/broker/broker.go
=> fixed minikube bug

config/manifests/default.yaml, config/samples/meshery_v1alpha1_broker.yaml, config/samples/meshery_v1alpha1_meshsync.yaml, go.mod, go.sum
=> bumped meshkit and manifest changes for version

README.md
Changed the first image displayed, the first one was broken.
=> Update README.md (Fix broken link)

README.md
Updated README community section and added the required text.
This PR fixes 
#161 
I also added the link of the `Community member form` with this [link](https://layer5.io/newcomer) provided in the issues section.
=> Updated README community section

.github/workflows/slack.yaml
Signed-off-by: debjani1413 <deydebjani916@gmail.com>
Updated the link in slack.yml from layer5io to meshery
=> Updated the slack.yml

.github/ISSUE_TEMPLATE/documentation.md, .github/PULL_REQUEST_TEMPLATE.md, .github/config.yml
Signed-off-by: Ayushman Mishra <ayushvidushi01@gmail.com>
Changing the layer5 link to meshery link
=> changes made meshery link

.github/dependabot.yml
Signed-off-by: Jash Patel <jashvpatel1@gmail.com>
This PR changes dependabot default reviewer.
=> changed depandabot reviewer

.github/workflows/newcomer-alert.yml
Signed-off-by: Ankita Pareek <ankitapareek2000@gmail.com>
- This PR adds a workflow to notify about good first issues on the #newcomer slack channel of Layer5. 
- The slack.yaml file is already up-to-date.
This PR fixes #233 
=> Added newcomers-alert.yml file to notify about good first issues on slack

.github/workflows/slack.yaml
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
This PR updates the slack workflow
=> [Cl] Update Slack Workflow

PROJECT
Signed-off-by: Suryashankar Das <suryashankardas.2002@gmail.com>
Version 3-alpha is deprecated
This PR is related to issue #220
=> bump version from 3-alpha to 3

README.md
Signed-off-by: Swapnil Bhabal <swapnilbhabal787@gmail.com>
Fixes #240 
Kindly review and let me know if any corrections, Thankyou.
=> The sheild is updated.

.gitignore, pkg/broker/resources.go
Signed-off-by: aisuko <urakiny@gmail.com>
=> Remove the host port defination on pod template

pkg/broker/resources.go
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
=> Update nats image

bundle/0.0.1/manifests/meshery-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/0.0.1/manifests/meshery-operator-metrics-service_v1_service.yaml, bundle/0.0.1/manifests/meshery-operator.clusterserviceversion.yaml, bundle/0.0.1/manifests/meshery.layer5.io_brokers.yaml, bundle/0.0.1/manifests/meshery.layer5.io_meshsyncs.yaml, bundle/0.0.1/metadata/annotations.yaml, bundle/0.0.1/tests/scorecard/config.yaml
Signed-off-by: Aisuko <urakiny@gmail.com>
Add bundle folder of operator community project to this repo. Because the CSV file is a littl bit different to the one was created by  `make bundle` command. So, we need to version control it.
=> Add bundle of operator

controllers/meshsync_controller.go
Reverts meshery/meshery-operator#356
=> Revert "Add support to configure broker service"

Makefile
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>
=> add repo to image name

README.md
Signed-off-by: Deborah Udoh <deborahudoh02@gmail.com>
This PR fixes issue #371 
The broken image was fixed by editing line 34, to change the file format (from SVG to PNG).  Thank you.
=> Fix broken image.

README.md
Signed-off-by: Deborah Udoh <deborahudoh02@gmail.com>
This PR fixes issue #371
This is an update for the recently-merged PR #373 
One image to support light and dark mode has been added.
=> Update community image.

controllers/broker_controller.go, controllers/meshsync_controller.go, main.go, pkg/broker/resources.go
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>
=> Perform correct cleanup using ownerReferences

.github/workflows/ci.yml, .golangci.yml
Replace golangci-lint configruation
=> Replace golangci-lint configruation

.github/workflows/ci.yml
This PR incorporates the running of golang unit tests and code coverage analysis.
1. CodeCov repo secret has been added to this repo.
1. CodeCov GitHub app has been enabled for this repo.
=> Include CodeCov

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/ci.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Updating Figma Open Invite Link in Docs

.github/config.yml
=> Logo Reference Updated in Github Workflow

README.md
=> Added Link to MeshSync in Readme

README.md
This PR fixes #510 
Signed-off-by : [jigarrathod2704@gmail.com](mailto:jigarrathod2704@gmail.com)
The new Meshery logo and tagline have been added to the README.md file.
=> The new Meshery logo and tagline have been added to the README.md file.

README.md
This PR fixes #530 
This PR fixed the building status badge. And the build action was fixed in the  #537 
=> Fixed build and release status badge

api/v1alpha1/meshsync_types.go, config/crd/bases/meshery.layer5.io_meshsyncs.yaml
=> update meshsync crd

.github/workflows/build-and-release.yml, .github/workflows/error-ref-publisher.yaml, .github/workflows/label-commenter.yml, .github/workflows/newcomer-alert.yml, .github/workflows/release-drafter.yml, .github/workflows/slack.yaml
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>
=> [ci][chore] upgrade workflow runner to ubuntu-24.04

README.md
=> Update README.md: youtube

.github/workflows/approve-to-run-ci.yml
=> Update runner to 24.04

.gemini/config.yaml
Signed-off-by: Lee Calcote <l@Office-iMac.local>
=> [CI] Disable Gemini

README.md
This PR fixes #607
-  Yes, I signed my commits.
=> Include 'meshery extensions' in help wanted issues link

.github/security-insights.yml
=> Add security insights configuration for Meshery-Operator

Makefile, README.md, bundle/0.0.1/manifests/meshery-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/default.yaml
Signed-off-by: Rian Cteulp <rian.cteulp@gmail.com>
=> Chore: Update docker image org

.github/workflows/error-ref-publisher.yaml
=> chore: rename meshkit rreference

controllers/broker_controller.go, controllers/broker_controller_test.go, controllers/meshsync_controller.go, controllers/meshsync_controller_test.go, controllers/suit_test.go, go.mod, go.sum, main.go, pkg/broker/broker.go, pkg/broker/broker_test.go, pkg/broker/suit_test.go, pkg/client/client.go, pkg/client/v1alpha1/broker.go, pkg/client/v1alpha1/meshsync.go, pkg/meshsync/meshsync.go, pkg/meshsync/meshsync_test.go
=> update package name

CONTRIBUTING.md
This pull request introduces a detailed `CONTRIBUTING.md` guide for the [Meshery Operator](https://github.com/meshery/meshery-operator), addressing the lack of contributor onboarding documentation highlighted in issue [#11112](https://github.com/meshery/meshery/issues/11112).
- ✅ Prerequisite setup (Go, Docker, Make, Git, Kubernetes)
- ✅ Local setup instructions (`git clone`, `make build`, `make run`, etc.)
- ✅ Project structure overview with folder roles explained
- ✅ Branching and contribution workflow (commit style, PR etiquette)
- ✅ Testing and linting instructions (`make test`, `make lint`)
- ✅ Helpful links to Meshery’s Slack and contribution handbook
Fixes #11112
> Not applicable. Markdown file addition only.
---
Looking forward to feedback! 🚀
This PR fixes #11112 …
=> docs: add comprehensive CONTRIBUTING.md for meshery-operator

.github/workflows/approve-to-run-ci.yml, .github/workflows/error-ref-publisher.yaml, CONTRIBUTING.md, Dockerfile, go.mod
This PR updates go to version 1.24
required by #628 
=> chore: upgrade go to version 1.24

integration-tests/main.sh
=> [integration-tests] issue #603: remove unused TEST namespace
